
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-request-router
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backend-request-router
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend-request-router
subjects:
- kind: ServiceAccount
  name: backend-request-router
  namespace: backend-request-router
