
---
kind: Service
apiVersion: v1
metadata:
  name: backend-request-router
  namespace: backend-request-router
spec:
  selector:
    app: backend-request-router
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
