
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-svc
  namespace: mock-svc
spec:
  selector:
    matchLabels:
      app: neon
  template:
    metadata:
      labels:
        app: neon

---
apiVersion: v1
kind: Service
metadata:
  name: mock-svc
  namespace: mock-svc
spec:
  selector:
    app: neon
